# Generated by Django 5.2.3 on 2025-06-18 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(help_text='Unique GRN identifier, can be auto-generated', max_length=50, unique=True)),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('received_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(limit_choices_to={'unit_type': 'BRANCH'}, on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='organization.businessunit')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns_received', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='products.supplier')),
            ],
            options={
                'verbose_name': 'Goods Receive Note (GRN)',
                'verbose_name_plural': 'Goods Receive Notes (GRNs)',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price_per_unit', models.DecimalField(decimal_places=2, help_text='Cost price for this specific shipment', max_digits=10)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.goodsreceivenote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(limit_choices_to={'unit_type': 'BRANCH'}, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='organization.businessunit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='products.product')),
            ],
            options={
                'verbose_name': 'Inventory Stock Level',
                'verbose_name_plural': 'Inventory Stock Levels',
                'ordering': ['branch', 'product'],
                'unique_together': {('branch', 'product')},
            },
        ),
    ]
