# Generated by Django 5.2.3 on 2025-06-18 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('sales', '0003_alter_sale_stock_deducted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('can_purchase_on_credit', models.BooleanField(default=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Automatically updated. Positive: Customer owes money. Negative: Customer has credit.', max_digits=12)),
                ('tax_id', models.CharField(blank=True, help_text="Customer's Tax ID / NTN", max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_owner', models.ForeignKey(help_text='The main organizational unit (Tenant Group or specific Company) this customer belongs to.', limit_choices_to={'unit_type__in': ['COMPANY', 'GROUP']}, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organization.businessunit')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('INVOICE', 'Sale Invoice (Credit)'), ('PAYMENT', 'Payment Received'), ('CREDIT_NOTE', 'Credit Note (Return/Refund)'), ('DEBIT_NOTE', 'Debit Note (Other Charges)'), ('OPENING', 'Opening Balance')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Increases amount customer owes', max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Decreases amount customer owes (e.g., payment)', max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='customers.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledger_entries_from_sale', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Customer Ledger Entry',
                'verbose_name_plural': 'Customer Ledger Entries',
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
