# Generated by Django 5.2.3 on 2025-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_options_sale_created_at_sale_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Indicates if stock was deducted for this sale.'),
        ),
    ]
