# Generated by Django 5.2.3 on 2025-06-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_owner', models.ForeignKey(help_text='The company in your organization that defines this category.', limit_choices_to={'unit_type': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='organization.businessunit')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('company_owner', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Retail, Wholesale, Take Away, Dine-In', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default price list for new products/branches?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_owner', models.ForeignKey(limit_choices_to={'unit_type': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='organization.businessunit')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company_owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_owner', models.ForeignKey(help_text='The company in your organization that manages this supplier relationship.', limit_choices_to={'unit_type': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organization.businessunit')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company_owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(choices=[('FINISHED', 'Finished Good'), ('RAW', 'Raw Material'), ('SERVICE', 'Service')], default='FINISHED', max_length=10)),
                ('is_inventory_tracked', models.BooleanField(default=True, help_text='If false, stock levels are not managed for this item (e.g., services).')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shelf_life_days', models.IntegerField(default=0, help_text='Shelf life in days. 0 means not applicable.')),
                ('allow_discount', models.BooleanField(default=True)),
                ('max_discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount allowed for this item in percentage (e.g., 10.00 for 10%)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('company_owner', models.ForeignKey(help_text='The company in your organization that owns this product definition.', limit_choices_to={'unit_type': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organization.businessunit')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.supplier')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company_owner', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text="Specific branch for this price. If blank, applies to all branches under the product's company owner.", limit_choices_to={'unit_type': 'BRANCH'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_product_prices', to='organization.businessunit')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
            options={
                'ordering': ['price_list', 'branch', 'product'],
                'unique_together': {('product', 'price_list', 'branch')},
            },
        ),
    ]
